const ALL_FAILED = "Nenhum provedor conseguiu responder para este registro.";

export const ENRICHMENT_STRINGS = {
  nav: "Enriquecimento",
  settings: {
    title: "Enriquecimento",
    description:
      "Conecte um provedor de pesquisa de leads para que o Preencher lacunas possa completar uma pessoa ou uma organização. Ativar um provedor envia o nome, email ou domínio do registro para esse provedor.",
    providersTitle: "Provedores",
    providersDescription: "As chaves são armazenadas criptografadas e nunca são exibidas novamente depois de salvas.",
    apiKeyLabel: "Chave de API",
    apiKeyPlaceholder: "Cole a chave",
    providerNames: {
      apollo: "Apollo",
      rocketreach: "RocketReach",
      getprospect: "GetProspect",
    },
    save: "Salvar chave",
    saving: "Salvando",
    remove: "Remover chave",
    removeConfirm: "Remover",
    removeConfirmTitle: "Remover esta chave de API?",
    removeConfirmBody:
      "O provedor é desativado e para de responder ao Preencher lacunas até que uma nova chave seja salva.",
    test: "Testar conexão",
    testCost:
      "Testar realiza uma busca de organização e uma de pessoa, então consome um crédito para cada uma.",
    testOk: "A chave funciona.",
    testNoMatch: "A chave funciona. O teste não encontrou dados, o que é normal.",
    testFailed: (verdict: string) => `Falha no teste: ${verdict}.`,
    testQuotaHourly: (left: number) => `${left} restantes nesta hora`,
    testQuotaDaily: (left: number) => `${left} restantes hoje`,
    testQuotaLine: (windows: string) => `Chamadas restantes: ${windows}.`,
    testLookupPerson: "buscas de pessoa",
    testLookupOrganization: "buscas de organização",
    testLookupSeparator: " ou ",
    testNotEntitledLine: (lookups: string) => `Este plano não inclui ${lookups}.`,
    testing: "Testando",
    enabledLabel: "Usar este provedor",
    needsKeyFirst: "Adicione uma chave de API primeiro",
    statusNoKey: "Sem chave",
    statusEnabled: "Ativado",
    statusDisabled: "Desativado",
    statusRejected: "Chave rejeitada",
    statusThrottled: (until: string) => `Limitado por taxa até ${until}`,
    statusQuota: (until: string) => `Sem créditos até ${until}`,
    keyHint: (hint: string) => `Chave terminando em ${hint}`,
    mappingTitle: "Mapeamento de campos",
    mappingDescription:
      "Onde cada dado do provedor é gravado. Tudo que não for mapeado nunca é gravado.",
    mappingPerson: "Pessoa",
    mappingOrganization: "Organização",
    mappingColField: "Campo do provedor",
    mappingColTarget: "Grava em",
    mappingNotMapped: "Não mapeado",
    mappingBuiltinGroup: "Campos padrão",
    mappingCustomGroup: "Campos personalizados",
    mappingNoCustomFields: "Ainda não há campos personalizados para esta entidade.",
    mappingManageFields: "Gerenciar campos de dados",
    cacheTitle: "Cache",
    cacheDescription:
      "Por quanto tempo um resultado é reaproveitado antes que um clique chame os provedores novamente. Zero desativa o cache.",
    cacheLabel: "Reaproveitar resultados por (dias)",
    cacheSave: "Salvar",
    cacheInvalid: "Informe um número inteiro de dias, de 0 a 365.",
    saveError: "Não foi possível salvar. Tente novamente.",
    adminOnly: "Somente um administrador pode configurar o enriquecimento.",
  },
  dialog: {
    title: (name: string) => `Preencher lacunas: ${name}`,
    loading: "Consultando os provedores conectados",
    subtitle: "Escolha o que gravar neste registro.",
    cached: (when: string) => `Enriquecido ${when}. Exibindo o resultado salvo.`,
    refresh: "Atualizar",
    apply: (count: number) => (count === 1 ? "Aplicar 1 campo" : `Aplicar ${count} campos`),
    applying: "Aplicando",
    cancel: "Cancelar",
    nothingFound: "Nada novo encontrado.",
    overwrites: (current: string) => `Substitui "${current}"`,
    overwritesHidden: "Substitui um valor ao qual você não tem acesso",
    relinksOrganization: (current: string) =>
      `Vincula esta pessoa a outra organização, substituindo "${current}"`,
    currentInvalid: (current: string) => `"${current}" não é um endereço válido`,
    primaryChoiceLabel: "Para onde vai",
    addAlongside: "Adicionar junto com o atual",
    addAsPrimary: "Adicionar e tornar principal",
    sources: "Fontes",
    sourceCount: (count: number) => (count === 1 ? "1 fonte" : `${count} fontes`),
    pickOne: "Os provedores divergem. Escolha um valor.",
    applyError: "Não foi possível aplicar. Nada foi alterado.",
    unresolvedOrgError:
      "Todo o resto foi aplicado. A organização não pôde ser vinculada porque nenhuma organização correspondente única foi encontrada; vincule manualmente.",
    staleError: "Este registro mudou enquanto você revisava. Atualize e tente novamente.",
    mappingsChangedError:
      "Um administrador alterou os campos em que o enriquecimento grava. Atualize e revise novamente.",
    runError: "Não foi possível contatar os provedores. Tente novamente.",
    allFailedError: ALL_FAILED,
    allFailedErrorReasons: (reasons: string) => `${ALL_FAILED} ${reasons}`,
    reasonSeparator: " · ",
    noIdentifierError:
      "Este registro não tem nada para buscar. Adicione um email, um domínio ou uma organização vinculada primeiro.",
    throttledError: (until: string) => `Todos os provedores estão limitados por taxa. Retomam em ${until}.`,
    throttledErrorUnknown: "Todos os provedores estão limitados por taxa. Tente novamente mais tarde.",
    unsupportedError:
      "Nenhum provedor conectado consegue buscar pelo que este registro possui. Adicione um email, um domínio ou o nome da organização à qual pertence.",
    notEntitledError:
      "Nenhum plano de provedor conectado inclui este tipo de busca. Faça upgrade do plano no provedor ou conecte outro provedor.",
    keyUnreadableError:
      "Uma chave de API salva não pôde ser lida. Um administrador precisa informá-la novamente em Configurações.",
    outcomeLine: (provider: string, verdict: string) => `${provider} ${verdict}`,
    outcomeLineUntil: (provider: string, verdict: string, until: string) =>
      `${provider} ${verdict} até ${until}`,
    ageJustNow: "agora mesmo",
    ageMinutes: (n: number) => (n === 1 ? "há 1 minuto" : `há ${n} minutos`),
    ageHours: (n: number) => (n === 1 ? "há 1 hora" : `há ${n} horas`),
    ageDays: (n: number) => (n === 1 ? "há 1 dia" : `há ${n} dias`),
  },
  button: {
    label: "Preencher lacunas",
    noIdentifier: "Adicione um email ou vincule uma organização primeiro",
    notConfigured: "Nenhum provedor de enriquecimento está conectado",
  },
  outcome: {
    ok: "ok",
    no_match: "sem correspondência",
    auth: "chave rejeitada",
    throttled: "limitado por taxa",
    quota: "sem créditos",
    timeout: "tempo esgotado",
    provider_error: "indisponível",
    skipped: "ignorado",
    unsupported: "sem identificador utilizável",
    key_unreadable: "chave não pôde ser lida",
    not_entitled: "não incluído neste plano",
  },
} as const;
