// Copy for the CSV import wizard (settings section 10). Extracted from strings.ts
// to keep that file under the 300-line hard cap; referenced as STRINGS.settings.importer.
export const IMPORTER_STRINGS = {
  title: "Importar dados",
  subtitle: "Importe pessoas, organizações, negócios, leads ou atividades de um arquivo CSV.",
  stepUpload: "Enviar",
  stepMap: "Mapear colunas",
  stepPreview: "Pré-visualizar",
  stepCommit: "Importar",
  chooseFile: "Arquivo CSV",
  dropzoneTitle: "Arraste e solte seu CSV aqui, ou clique para escolher",
  dropzoneHint: "Arquivos CSV de até 25 MB",
  fileTooLarge: "Esse arquivo é muito grande. Envie um CSV com menos de 25 MB.",
  entity: "Importar como",
  person: "Pessoas",
  organization: "Organizações",
  deal: "Negócios",
  lead: "Leads",
  activity: "Atividades",
  rowsDetected: (n: number) => `${n} linhas detectadas`,
  continue: "Continuar",
  dedup: "Quando um contato correspondente já existir",
  dedupSkip: "Pular a linha",
  dedupUpdate: "Atualizar o contato existente",
  column: "Coluna do CSV",
  mapTo: "Mapeia para",
  unmapped: "Não importar",
  customGroup: "Campos personalizados",
  nameRequired: "Mapeie uma coluna para Nome para continuar.",
  rowNote: "Adicionar colunas não mapeadas como nota",
  rowNoteHint:
    "Colunas que você não mapear são descartadas. Mantenha-as como uma nota em cada registro.",
  valid: (n: number) => `${n} válidas`,
  withErrors: (n: number) => `${n} com erros`,
  rowErrors: "Linhas com erros",
  commitButton: (n: number) => `Importar ${n} linhas válidas`,
  importing: "Importando...",
  result: (imported: number, skipped: number, invalid: number) =>
    `${imported} importadas, ${skipped} puladas, ${invalid} com falha`,
  statusCompleted: "Importação concluída",
  statusPartial: "Importação parcialmente concluída",
  statusFailed: "Importação falhou",
  errorGeneric: "Algo deu errado. Tente novamente.",
  requiresImport: "Você não tem permissão para importar dados.",
  importLeads: "Importar leads",
  startOver: "Importar outro arquivo",
  newImport: "Nova importação",
  historyEmpty: "Nenhuma importação ainda.",
  colFile: "Arquivo",
  colTarget: "Tipo",
  colWhen: "Quando",
  colStatus: "Status",
  colResult: "Resultado",
  colActions: "",
  downloadErrors: "Baixar erros",
  undo: "Desfazer",
  undoing: "Desfazendo...",
  undone: "Desfeito",
  resultCounts: (imported: number, errors: number) => `${imported} importadas, ${errors} erros`,
} as const;
