import { IMPORTER_STRINGS } from "./importerStrings";

export const SETTINGS_STRINGS = {
  permissionSets: "Conjuntos de permissão",
  permissionSetsDescription: "Defina conjuntos de permissão reutilizáveis para papéis e times.",
  visibilityGroups: "Grupos de visibilidade",
  visibilityGroupsDescription:
    "Controle quais grupos podem ver quais registros em todo o workspace.",
  teams: "Equipes",
  teamsDescription: "Organize usuários em equipes e defina gestores.",
  goals: "Metas",
  goalsDescription:
    "Defina cotas para um vendedor, uma equipe ou a empresa toda, e acompanhe o atingimento na página de Desempenho.",
  goalNew: "Nova meta",
  goalSubject: "Medida",
  goalAction: "Evento",
  goalMetric: "Contado por",
  goalAssignee: "Aplica-se a",
  goalPipeline: "Pipeline",
  goalActivityType: "Tipo de atividade",
  goalInterval: "Repete",
  goalTarget: "Alvo",
  goalStartsOn: "Início",
  goalEndsOn: "Fim",
  goalAnyPipeline: "Todos os pipelines",
  goalAnyActivityType: "Qualquer tipo",
  goalNoEnd: "Sem data de término",
  goalCreate: "Criar meta",
  goalEdit: "Editar",
  goalSave: "Salvar alterações",
  goalDelete: "Excluir",
  goalDeleteConfirm:
    "Excluir esta meta? O progresso já reportado contra ela vai desaparecer da página de Desempenho.",
  goalsEmpty: "Nenhuma meta ainda.",
  goalInvalid:
    "Essa combinação não é uma meta que conseguimos medir. Verifique o evento e como ele é contado.",
  goalSaveFailed: "Não foi possível salvar a meta.",
  products: "Produtos",
  productsDescription:
    "Mantenha o catálogo de produtos e serviços usados para precificar negócios.",
  automations: "Automações",
  automationsDescription:
    "Crie atividades, envie notificações e e-mails, ou atualize campos automaticamente quando um negócio muda.",
  productNew: "Novo produto",
  productName: "Nome",
  productSku: "SKU",
  productPrice: "Preço",
  productUnit: "Unidade",
  productDescription: "Descrição",
  productCreate: "Criar produto",
  productEdit: "Editar",
  productSave: "Salvar alterações",
  productArchive: "Arquivar",
  productArchiveConfirm:
    "Arquivar este produto? Ele continua nos negócios que já o usam, mas não vai mais aparecer ao adicionar novos itens.",
  productsEmpty: "Nenhum produto ainda.",
  productInvalid: "Verifique o nome e o preço do produto.",
  productSaveFailed: "Não foi possível salvar o produto.",
  productSkuExists: "Outro produto já usa este SKU.",
  users: "Usuários",
  usersDescription: "Convide usuários, revise acessos e mantenha as licenças ativas em dia.",
  notifications: "Notificações",
  notificationsDescription:
    "Escolha quais atualizações de atividade aparecem no app ou por e-mail.",
  requiresAdmin: "Esta ação requer um administrador.",
  requiresAuth: "Faça login para ver esta página.",
  profile: "Preferências pessoais",
  profileDescription:
    "Atualize os dados da sua conta, foto, fuso horário e preferências de interface.",
  name: "Nome",
  email: "E-mail",
  timezone: "Fuso horário",
  timezoneNone: "Usar padrão do navegador",
  density: "Densidade da interface",
  comfortable: "Confortável",
  compact: "Compacta",
  scheduleFollowUpAfterWon: "Agendar uma atividade de follow-up ao marcar um negócio como Ganho",
  interfaceHeading: "Interface",
  interface: {
    openDetailsAfterCreate: "Abrir a visualização de detalhes após criar um novo item",
    openDetailsLeadDeal: "Lead/negócio",
    openDetailsPerson: "Pessoa",
    openDetailsOrg: "Organização",
    usPhoneFormat: "Converter números de telefone para o formato dos EUA",
    winSound: "Tocar um som de moedas após cada negócio ganho",
    emailLinksNewTab: "Abrir links de e-mail em uma nova aba",
    prefillParticipantsAsRecipients:
      "Preencher automaticamente todos os participantes do negócio como destinatários de e-mail",
    autoPrefixLeadDealTitles:
      'Adicionar automaticamente "lead" e "negócio" aos títulos de leads/negócios',
  },
  dailyActivityTarget: {
    heading: "Meta diária de atividades",
    description:
      "Quantas atividades por dia devem ser feitas antes de o dia ser considerado completo. Isso só colore os indicadores de dia nos seletores de data de atividades, nunca limita quantas atividades você pode adicionar.",
    label: "Atividades por dia",
  },
  save: "Salvar",
  saved: "Salvo",
  saveName: "Salvar nome",
  photo: "Foto",
  uploadPhoto: "Enviar foto",
  changePhoto: "Trocar foto",
  removePhoto: "Remover",
  photoHint: "PNG, JPEG, WebP ou GIF, até 2 MB.",
  photoInvalidType: "Escolha uma imagem PNG, JPEG, WebP ou GIF.",
  photoTooLarge: "Essa imagem é muito grande (máx. 2 MB).",
  photoFailed: "Não foi possível atualizar sua foto. Tente novamente.",
  myAccount: "Minha conta",
  companyOverview: "Visão geral da empresa",
  companySettings: "Configurações da empresa",
  companySettingsDescription:
    "Gerencie padrões do workspace, catálogos de atividades, motivos de perda e etiquetas.",
  emailSync: "Sincronização de e-mail",
  connectedApps: "Apps conectados",
  connectedAppsDescription: "Revise e revogue apps que podem acessar o Warpdrive como sua conta.",
  connectedAppsList: "Apps autorizados",
  connectedAppsListDescription: "Cada app usa suas permissões atuais no CRM.",
  connectedAppsEmpty: "Nenhum app conectado ainda.",
  connectedAppsRevoke: "Revogar",
  connectedAppsRevoking: "Revogando...",
  connectedAppsRevokeError: "Não foi possível revogar esta conexão. Tente novamente.",
  connectedAppsConnected: (date: string) => `Conectado em ${date}`,
  connectedAppsLastUsed: (date: string) => `Último uso em ${date}`,
  connectedAppsNeverUsed: "Ainda não usado",
  dataFields: "Campos de dados",
  emailTemplates: "Modelos de e-mail",
  signatures: "Assinaturas",
  importData: "Importar dados",
  companyGeneral: "Geral",
  companyName: "Nome da empresa",
  baseCurrency: "Moeda base",
  activities: "Atividades",
  lostReasons: "Motivos de perda",
  labels: "Etiquetas",
  pipelines: "Pipelines",
  pipelinesDescription: "Crie pipelines e gerencie suas etapas.",
  createPipeline: "Criar pipeline",
  pipelineNameLabel: "Nome do pipeline",
  pipelineNamePlaceholder: "ex.: Pipeline de Vendas",
  createPipelineDescription:
    "Novos pipelines começam com um conjunto padrão de etapas que você pode editar.",
  createPipelineError: "Não foi possível criar o pipeline. Tente novamente.",
  noPipelinesYet: "Nenhum pipeline ainda.",
  editStages: "Editar etapas",
  creating: "Criando...",
  createFirstPipeline: "Crie seu primeiro pipeline",
  add: "Adicionar",
  cancel: "Cancelar",
  rename: "Renomear",
  delete: "Excluir",
  archive: "Arquivar",
  moveUp: "Mover para cima",
  moveDown: "Mover para baixo",
  enable: "Ativar",
  disable: "Desativar",
  enabled: "Ativado",
  disabled: "Desativado",
  systemBadge: "Sistema",
  emptyList: "Nada aqui ainda.",
  addActivityType: "Adicionar tipo de atividade",
  activityTypeName: "Nome do tipo de atividade",
  iconLabel: "Ícone",
  deleteTypeBlocked: "Não é possível excluir: este tipo de atividade é do sistema ou está em uso.",
  addLostReason: "Adicionar motivo de perda",
  lostReasonName: "Motivo de perda",
  addLabel: "Adicionar etiqueta",
  labelName: "Nome da etiqueta",
  color: "Cor",
  deleteLabelBlocked: "Não é possível excluir: esta etiqueta está aplicada a um ou mais registros.",
  targetDeal: "Negócios",
  targetPerson: "Pessoas",
  targetOrganization: "Organizações",
  targetLead: "Leads",
  entity: "Entidade",
  fieldName: "Nome do campo",
  fieldType: "Tipo",
  fieldOptions: "Opções",
  fieldOptionsHelp: "Rótulos de opção separados por vírgula",
  addField: "Adicionar campo",
  fieldOptionsRequired: "Adicione ao menos uma opção para um campo do tipo opção.",
  addFieldFailed: "Não foi possível adicionar o campo. Tente novamente.",
  noFields: "Nenhum campo personalizado ainda.",
  builtinFields: "Campos nativos",
  customFields: "Campos personalizados",
  builtinBadge: "Nativo",
  builtinAlwaysShown: "Sempre exibido",
  builtinHidden: "Oculto",
  builtinHideNote:
    "Ocultar um campo nativo o remove dos formulários de adição, do detalhe do registro e do mapeamento de importação. Os dados são mantidos e reaparecem quando você reexibi-lo.",
  builtinHideFailed: "Não foi possível atualizar o campo. Tente novamente.",
  entityDeal: "Negócio",
  entityPerson: "Pessoa",
  entityOrganization: "Organização",
  entityActivity: "Atividade",
  dragHandle: "Arraste para reordenar",
  important: "Importante",
  showInAddForm: "Exibir no formulário de adição",
  editOptions: "Editar opções",
  optionLabel: "Rótulo da opção",
  removeOption: "Remover",
  newOption: "Nova opção",
  addOption: "Adicionar opção",
  optionArchived: "Arquivada",
  columns: {
    name: "Nome",
    email: "E-mail",
    role: "Papel",
    active: "Ativo",
    flagsEnabled: "Permissões ativadas",
    default: "Padrão",
    created: "Criado",
    manager: "Gestor",
  },
  values: {
    admin: "Administrador",
    regular: "Comum",
    yes: "Sim",
    no: "Não",
    none: "Nenhum",
  },
  importer: IMPORTER_STRINGS,
} as const;
