// Centralized UI copy (ops spec E7: English-only v1, but no hardcoded text in components,
// so a future locale layer is a drop-in). No em dashes anywhere.
import { DEAL_SIDEBAR_STRINGS } from "./dealSidebarStrings";
import { ENRICHMENT_STRINGS } from "./enrichmentStrings";
import { INBOX_STRINGS } from "./inboxStrings";
import { SETTINGS_STRINGS } from "./settingsStrings";

export const STRINGS = {
  app: { name: "Warpdrive" },
  nav: {
    pipeline: "Pipeline",
    leads: "Leads",
    deals: "Negócios",
    contacts: "Contatos",
    people: "Pessoas",
    orgs: "Organizações",
    contactsTimeline: "Linha do tempo",
    activities: "Atividades",
    inbox: "Caixa de entrada",
    dashboard: "Desempenho",
    settings: "Configurações",
  },
  auth: {
    signInWithGoogle: "Entrar com o Google",
    loginTitle: "Entrar no Warpdrive",
    domainOnly: "Use a conta do Google Workspace da sua empresa.",
    emailPlaceholder: "seu@email.com",
    sendMagicLink: "Enviar link de acesso",
    magicLinkSent: "Link enviado! Confira seu e-mail.",
    magicLinkInvalidEmail: "E-mail inválido.",
    magicLinkAuthFailed: "O link expirou ou já foi usado. Peça um novo.",
    orDivider: "ou",
  },
  contacts: {
    peopleHeading: "Pessoas",
    colName: "Nome",
    colOrg: "Organização",
    colEmail: "E-mail",
    colPhone: "Telefone",
    colClosedDeals: "Negócios fechados",
    empty: "Nenhuma pessoa visível para você ainda.",
    orgsHeading: "Organizações",
    orgsEmpty: "Nenhuma organização visível para você ainda.",
    colAddress: "Endereço",
    colPeopleCount: "Pessoas",
    colDealCount: "Negócios",
    colOpenDeals: "Negócios em aberto",
    countLabel: (shown: number, total: number) => `Mostrando ${shown} de ${total}`,
    addPerson: "+ Pessoa",
    addOrg: "+ Organização",
    nameLabel: "Nome",
    add: "Adicionar",
    cancel: "Cancelar",
    timelineHeading: "Linha do tempo de contatos",
    timelineEmpty: "Nenhuma atividade recente de contato.",
  },
  leads: {
    contactPerson: "Pessoa de contato",
    searchAddPerson: "Buscar ou adicionar uma pessoa",
    addAsNewPerson: (q: string) => `Adicionar '${q}' como nova pessoa`,
    similarContact: "Já existe um contato semelhante.",
    organization: "Organização",
    searchAddOrg: "Buscar ou adicionar uma organização",
    addAsNewOrg: (q: string) => `Adicionar '${q}' como nova organização`,
    similarOrg: "Já existe uma organização semelhante.",
    titleLabel: "Título",
    leadTitle: "Título do lead",
    valueLabel: "Valor",
    leadValue: "Valor do lead",
    valuePlaceholder: "0",
    labelsLabel: "Etiquetas",
    ownerLabel: "Responsável",
    ownerMe: "Eu",
    expectedCloseDate: "Data prevista de fechamento",
    sourceChannel: "Canal de origem",
    noSourceChannel: "Sem canal de origem",
    sourceChannelId: "ID do canal de origem",
    sourceChannelIdPlaceholder: "Referência / ID da campanha",
    visibleTo: "Visível para",
    visibleToDefault: "Padrão",
    emptyTitle: "Nenhum lead ainda",
    emptyBody:
      "Um lead é uma oportunidade não qualificada que você trabalha antes de ela ganhar um lugar no pipeline.",
    emptyAction: "Adicionar lead",
    emptyArchivedTitle: "Nada no arquivo",
    emptyArchivedBody:
      "Arquivar um lead o remove da caixa de entrada sem excluí-lo. Nada está arquivado no momento.",
    emptyArchivedAction: "Voltar para a caixa de entrada",
    emptyFilteredTitle: "Nenhum lead corresponde a esses filtros",
    // Every count the inbox has is already narrowed by the filter, so this sentence cannot claim
    // leads exist behind it. It has to be true of an empty inbox too.
    emptyFilteredBody:
      "Os filtros acima são a única coisa restringindo esta visualização. Limpe-os para ver tudo.",
    emptyFilteredAction: "Limpar filtros",
  },
  reconnect: { reconnecting: "Reconectando..." },
  dealSidebar: DEAL_SIDEBAR_STRINGS,
  enrichment: ENRICHMENT_STRINGS,
  inbox: INBOX_STRINGS,
  notifications: {
    title: "Notificações",
    markAllRead: "Marcar todas como lidas",
    seeAll: "Ver toda a atividade",
    today: "Hoje",
    earlier: "Anteriores",
    empty: "Nenhuma notificação ainda.",
    labels: {
      mention: "Você foi mencionado",
      activity_assigned: "Atividade atribuída",
      activity_reminder: "Lembrete",
      deal_followed_update: "Atualização",
      deal_followed_update_fallback: "um negócio seguido foi alterado",
      email_open: "Seu e-mail foi aberto",
      email_click: "Um link do seu e-mail foi clicado",
      deal_won: "Um negócio que você segue foi ganho",
      deal_lost: "Um negócio que você segue foi perdido",
      comment_reply: "Nova resposta a um comentário",
      deal_email_received: "Novo e-mail",
      deal_email_received_fallback: "em um negócio",
      automation: "Automação executada",
      fallback: "Notificação",
    },
    preferences: {
      pageTitle: "Preferências de notificação",
      loading: "Carregando preferências...",
      columnInApp: "No app",
      columnEmail: "E-mail",
      saveError: "Falha ao salvar preferência. Tente novamente.",
      typeLabels: {
        mention: "Menções",
        activity_assigned: "Atividade atribuída a mim",
        activity_reminder: "Lembretes de atividade",
        deal_followed_update: "Atualizações de negócios seguidos",
        email_open: "E-mail aberto",
        email_click: "Link do e-mail clicado",
        deal_won: "Negócio ganho",
        deal_lost: "Negócio perdido",
        comment_reply: "Respostas a comentários",
        deal_email_received: "Novo e-mail nos meus negócios",
        automation: "Automação executada",
      },
    },
  },
  dashboard: {
    title: "Desempenho",
    ownerToggleLabel: "Responsável:",
    ownerMe: "Eu",
    ownerAll: "Todos",
    ownerToggleTitle: "Alternar escopo de responsável",
    ownerToggleDisabledTitle: "Você só pode ver suas próprias estatísticas",
    loading: "Carregando...",
    statsUnavailable: "Estatísticas indisponíveis.",
    widgetDealPerformance: "DESEMPENHO DE NEGÓCIOS",
    widgetFunnelConversion: "CONVERSÃO DO FUNIL",
    widgetActivities: "DESEMPENHO DE ATIVIDADES",
    widgetStageSums: "SOMA DE VALOR POR ETAPA",
    added: "Adicionados",
    won: "Ganhos",
    lost: "Perdidos",
    open: "Em aberto",
    completed: "Concluídas",
    scheduled: "Agendadas",
    undated: "Sem prazo",
    rangeStartLabel: "Início do período",
    rangeEndLabel: "Fim do período",
    rangeSeparator: "até",
    pipelineLabel: "Pipeline",
    allPipelines: "Todos os pipelines",
    widgetScoreboard: "PLACAR",
    widgetActivityTypes: "ATIVIDADES POR TIPO",
    widgetLostReasons: "MOTIVOS DE PERDA",
    widgetGoals: "METAS",
    scoreWon: "Negócios ganhos",
    scoreWinRate: "Taxa de vitória",
    scoreAvgDeal: "Ticket médio ganho",
    scoreCycle: "Ciclo de vendas mediano",
    scoreActivities: "Atividades concluídas",
    days: "dias",
    noValue: "-",
    // A duration that rounds to zero days is shorter than the unit reported here, not instant.
    underADay: "Menos de um dia",
    emptyGoalsBody:
      "Uma meta define um alvo para uma pessoa ou para a equipe em um período que você escolhe.",
    emptyFunnel: "Nenhum negócio foi criado nesse período, então não há funil para medir.",
    emptyStageSums: "Nenhum negócio em aberto nessas etapas.",
    emptyActivityTypes: "Nenhum tipo de atividade configurado.",
    emptyLostReasons: "Nenhum negócio foi perdido nesse período.",
    emptyGoals: "Nenhuma meta se aplica a você ainda.",
    goalsSettingsLink: "Configurar metas",
    lostReasonUnspecified: "Nenhum motivo registrado",
    goalPeriod: "Período",
    goalTarget: "Meta",
    goalPace: "Ritmo",
    goalNotStarted: "Fora do período desta meta",
    goalBooked: "Realizado",
    goalTargetPace: "No ritmo",
    widgetWonTrend: "NEGÓCIOS GANHOS POR MÊS",
    emptyWonTrend: "Nenhum negócio foi ganho nesse período, então não há tendência para mostrar.",
    trendTableCaption: "Negócios ganhos por mês",
    trendMonth: "Mês",
    trendCount: "Negócios ganhos",
    trendValue: "Valor ganho",
    widgetForecast: "PREVISÃO POR MÊS DE FECHAMENTO ESPERADO",
    emptyForecast:
      "Nenhum negócio em aberto nesse período tem data de fechamento esperada, então não há previsão para mostrar.",
    forecastTableCaption: "Negócios em aberto por mês de fechamento esperado",
    forecastMonth: "Mês",
    forecastCount: "Negócios em aberto",
    forecastValue: "Valor total",
    forecastWeightedValue: "Ponderado (pela probabilidade da etapa)",
    // The funnel is a cohort measure and the board is a live snapshot, so the two disagree by
    // design. The widget has to say which cohort it counted or the gap reads as a bug.
    funnelBasisMe: "Conta apenas negócios seus criados nesse período.",
    funnelBasisAll: "Conta negócios criados nesse período, independente do responsável.",
  },
  search: {
    placeholder: "Buscar negócios, pessoas, organizações, leads...",
    idle: "Digite para buscar",
    resultsLabel: "Resultados da busca",
    headingDeals: "Negócios",
    headingPeople: "Pessoas",
    headingOrganizations: "Organizações",
    headingLeads: "Leads",
    emptyDeals: "Nenhum negócio",
    emptyPeople: "Nenhuma pessoa",
    emptyOrganizations: "Nenhuma organização",
    emptyLeads: "Nenhum lead",
  },
  // Copy for the route error / not-found boundaries. Deliberately vague about the cause: in
  // production Next redacts the message, and the digest is the operator's only handle to the log.
  errors: {
    notFound: "Não encontrado",
    forbidden: "Você não tem permissão para fazer isso.",
    boundaryTitle: "Algo deu errado",
    boundaryBody:
      "Esta página encontrou um erro inesperado. Tentar novamente pode resolver; se persistir, informe a referência abaixo.",
    referenceLabel: "Referência:",
    retry: "Tentar novamente",
    appCrashTitle: "O Warpdrive não conseguiu iniciar",
    appCrashBody: "Recarregue a página. Se persistir, verifique os logs do servidor.",
    reload: "Recarregar",
    notFoundBody: "Esse registro não existe, ou você não tem acesso a ele.",
    backToPipeline: "Voltar ao pipeline",
  },
  board: {
    sort: {
      label: "Ordenar por",
      ascending: "Ordenar crescente",
      descending: "Ordenar decrescente",
      options: {
        nextActivity: "Próxima atividade",
        title: "Título do negócio",
        value: "Valor do negócio",
        person: "Pessoa vinculada",
        organization: "Organização vinculada",
        updateTime: "Data de atualização do negócio",
        owner: "Nome do responsável",
      },
    },
    // Screen-reader announcements for board drags (aria-live).
    announcements: {
      pickedUp: (title: string, stage: string): string =>
        `Peguei ${title}${stage !== "" ? `, ${stage}` : ""}`,
      notOverColumn: "Fora de uma coluna",
      movedTo: (stage: string): string => `Movido para ${stage}`,
      droppedIn: (stage: string): string => `Solto em ${stage}`,
      cancelled: "Cancelado",
    },
  },
  dealsList: {
    emptyTitle: "Nenhum negócio neste pipeline ainda",
    emptyBody:
      "Um negócio é uma oportunidade: um valor, uma etapa e um responsável. O primeiro que você adicionar aparece aqui e no quadro.",
    emptyArchivedTitle: "Nada arquivado",
    emptyArchivedBody:
      "Arquivar um negócio o remove do quadro sem excluí-lo. Tudo que você arquiva aparece aqui, pronto para restaurar.",
    emptyArchivedAction: "Voltar ao quadro",
    emptyFilteredTitle: "Nenhum negócio corresponde a este filtro",
    emptyFilteredBody: "O pipeline ainda tem negócios. Os filtros acima excluem todos eles.",
    emptyFilteredAction: "Limpar filtros",
  },
  calendar: {
    emptyTitle: (view: string) =>
      `Nada agendado para ${view === "month" ? "este mês" : "esta semana"}`,
    emptyBody:
      "Somente atividades com prazo nesta janela aparecem aqui. Vá para outra semana ou mês para ver o resto.",
    emptyAction: "Adicionar atividade",
    emptyFilteredTitle: (view: string) =>
      `Nenhuma atividade corresponde a esses filtros ${view === "month" ? "este mês" : "esta semana"}`,
    emptyFilteredBody: "Esta janela tem atividades. Os filtros acima excluem todas elas.",
    emptyFilteredAction: "Limpar filtros",
  },
  titles: {
    calendar: "Calendário",
    dealList: "Lista de negócios",
    editPipeline: "Editar pipeline",
    // Fallbacks when a detail entity has no name yet or is not visible. The pipeline board's
    // fallback reuses nav.pipeline (same word, one source).
    dealFallback: "Negócio",
    leadFallback: "Lead",
    personFallback: "Pessoa",
    orgFallback: "Organização",
  },
  settings: SETTINGS_STRINGS,
} as const;
